<!DOCTYPE html>
<head>
  <title>Infostander Aarhus</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="/css/infostanderaarhus.styles.css">
  <link rel="stylesheet" href="/css/infostander-icons.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
  <script src="/scripts/scrolling.min.js" type="application/javascript"></script>
  <!--[if lt IE 9]>
  <link rel="stylesheet" href="/css/ie8.css">
  <script src="/scripts/html5shiv.js"></script>
  <![endif]-->
</head>